-- =============================================================================
-- Migration 001: Tablas del sistema de Recepción de Carnes (Res y Cerdo)
-- Ejecutar en el SQL Editor de Supabase (una sola vez, en orden)
-- =============================================================================
--
-- El modelo sale de los dos Excel que usa el admin hoy:
--   · Res   — "01 Septiembre 2026.xlsx": hoja `Datos ` (maestro + gastos) y una
--             hoja por sede. UN lote de novillos se reparte entre VARIAS sedes.
--   · Cerdo — "1. Principal.xlsm": hojas `ITEMS` y `Plantilla`. Un documento por
--             sede, un solo juego de kilos.
--
-- Los dos corren EL MISMO cálculo (ver src/shared/costeo.js). La diferencia es
-- cuántas sedes cuelgan del documento, así que el esquema modela el caso de Res
-- —N sedes— y el de cerdo es simplemente N=1. Al revés no funcionaba.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. carnes_sedes — Catálogo de sedes + el token del QR de verificación
-- ---------------------------------------------------------------------------
--
-- `qr_token` es lo que lleva impreso el código QR pegado en la zona de recibo.
-- Es un valor opaco y aleatorio, NO el nombre de la sede: si el QR dijera
-- "Villahermosa" en texto plano, cualquiera lo escribe a mano desde la casa y la
-- verificación no verifica nada.
--
-- Se guarda en la base (en vez de firmarlo con HMAC) porque así se puede REVOCAR
-- al instante: si un QR se filtra o alguien le saca una foto, se regenera el
-- token, se reimprime el sticker, y el viejo deja de servir en la siguiente
-- petición. Con una firma HMAC habría que rotar el secreto de TODAS las sedes.
CREATE TABLE IF NOT EXISTS carnes_sedes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_co   VARCHAR(10),              -- Centro de Operación de SIESA ('01'..'08')
  nombre      VARCHAR(80)   NOT NULL,
  qr_token    VARCHAR(64)   NOT NULL DEFAULT replace(gen_random_uuid()::text, '-', ''),
  activo      BOOLEAN       NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- UNIQUE, no un índice común: dos sedes con el mismo token es exactamente el
-- error que este sistema existe para impedir.
CREATE UNIQUE INDEX IF NOT EXISTS idx_carnes_sedes_qr_token ON carnes_sedes(qr_token);
CREATE UNIQUE INDEX IF NOT EXISTS idx_carnes_sedes_nombre   ON carnes_sedes(lower(nombre));


-- ---------------------------------------------------------------------------
-- 2. carnes_plantilla_items — El maestro que edita el admin
-- ---------------------------------------------------------------------------
--
-- Espejo de la hoja `Datos ` (res) y `ITEMS` (cerdo).
--
-- `orden` es la columna que manda en la pantalla del recibidor: el admin arma la
-- lista en el orden en que la carne baja del camión, y ese orden se respeta tal
-- cual. Si se ordenara por código o alfabéticamente, el recibidor tendría que
-- buscar cada ítem en la lista mientras sostiene una canasta.
--
-- `codigo_item` es el f120_id de SIESA y NO es único: en el Excel de res, varias
-- descripciones comparten código (CARNE PARA MOLER y COGOTE son ambas 15167).
-- Lo único único por especie es `codigo_tabla` (el "Item Proveedor", 1..N).
CREATE TABLE IF NOT EXISTS carnes_plantilla_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  especie       VARCHAR(10)     NOT NULL CHECK (especie IN ('res', 'cerdo')),
  codigo_tabla  INTEGER         NOT NULL,           -- "Item Proveedor" / Cod. Tabla
  codigo_item   VARCHAR(20)     NOT NULL,           -- f120_id de SIESA
  descripcion   TEXT            NOT NULL,
  costo_base    NUMERIC(14,2)   NOT NULL DEFAULT 0, -- "Costo Proveedor" / "Último costo tradicional"
  orden         INTEGER         NOT NULL DEFAULT 0,
  activo        BOOLEAN         NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_carnes_plantilla_especie_tabla
  ON carnes_plantilla_items(especie, codigo_tabla);
CREATE INDEX IF NOT EXISTS idx_carnes_plantilla_orden
  ON carnes_plantilla_items(especie, activo, orden);


-- ---------------------------------------------------------------------------
-- 3. carnes_viceras_items — Catálogo de vísceras (bonificación)
-- ---------------------------------------------------------------------------
--
-- El Excel de res tiene DOS bloques de vísceras y hacen cosas distintas:
--
--   · bloque = 'bonificacion' (filas 44-48: Vísceras, Mondongo, Lengua,
--     Chunchulla, Entrañita) — se valoriza y se RESTA del costo real de la sede,
--     pero solo si el toggle `Sumar Viceras (SI/NO)` está en SI.
--
--   · bloque = 'informativo' (filas 52-57: Hígado, Riñón, Corazón, Bofe,
--     Pajarilla, Punta de falda) — en el Excel se calcula por novillo y NO entra
--     en ningún total. Se conserva porque el admin lo mira, pero no toca plata.
--
-- Si se mezclaran en un solo bloque, el informativo empezaría a descontar de la
-- factura y el costo de cada corte saldría más barato de lo que costó.
CREATE TABLE IF NOT EXISTS carnes_viceras_items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  especie     VARCHAR(10)     NOT NULL CHECK (especie IN ('res', 'cerdo')),
  bloque      VARCHAR(20)     NOT NULL CHECK (bloque IN ('bonificacion', 'informativo')),
  nombre      VARCHAR(80)     NOT NULL,
  precio      NUMERIC(14,2)   NOT NULL DEFAULT 0,
  orden       INTEGER         NOT NULL DEFAULT 0,
  activo      BOOLEAN         NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_viceras_especie
  ON carnes_viceras_items(especie, bloque, activo, orden);


-- ---------------------------------------------------------------------------
-- 4. carnes_conceptos_gasto — Catálogo de conceptos de gasto
-- ---------------------------------------------------------------------------
--
-- Res  (`Datos `!O5:O15): Ganado, Fletes, Interés mk, Sacrificio, Retomas
--      Sacrificio, Desposte y Empacado, Retomas Desposte, Servicio de compra.
-- Cerdo (`Plantilla`!F6:F9): Valor de la carne, Valor Servicios, Transporte,
--      Retomas.
--
-- `signo` existe por las RETOMAS. En el Excel de cerdo el total es
-- `SUM(G6:G8) - G9`: los tres primeros suman y las retomas restan. Sin esta
-- columna, una retoma cargada como gasto positivo infla el costo real, y el
-- costo de cada corte sale más caro de lo que fue.
CREATE TABLE IF NOT EXISTS carnes_conceptos_gasto (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  especie     VARCHAR(10)   NOT NULL CHECK (especie IN ('res', 'cerdo')),
  nombre      VARCHAR(80)   NOT NULL,
  signo       SMALLINT      NOT NULL DEFAULT 1 CHECK (signo IN (1, -1)),
  orden       INTEGER       NOT NULL DEFAULT 0,
  activo      BOOLEAN       NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_conceptos_especie
  ON carnes_conceptos_gasto(especie, activo, orden);


-- ---------------------------------------------------------------------------
-- 5. carnes_liquidaciones — El documento de costeo (una hoja `Datos ` completa)
-- ---------------------------------------------------------------------------
--
-- Agrupa TODAS las recepciones de una misma entrega. Es el nivel donde viven los
-- gastos, el costo promedio por kilo y el % de participación por sede — datos
-- que no existen a nivel de una sola sede porque se calculan contra el total.
--
-- `viceras_bonificacion` es el toggle `Sumar Viceras (SI/NO)` de `Datos `!D50.
CREATE TABLE IF NOT EXISTS carnes_liquidaciones (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  especie               VARCHAR(10)   NOT NULL CHECK (especie IN ('res', 'cerdo')),
  fecha                 DATE          NOT NULL DEFAULT current_date,
  proveedor             VARCHAR(120),
  viceras_bonificacion  BOOLEAN       NOT NULL DEFAULT false,
  estado                VARCHAR(30)   NOT NULL DEFAULT 'Abierta'
                          CHECK (estado IN ('Abierta', 'Costeada', 'Cerrada')),
  observaciones         TEXT,
  created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_liquidaciones_fecha
  ON carnes_liquidaciones(especie, fecha DESC);


-- ---------------------------------------------------------------------------
-- 6. carnes_liquidacion_gastos — Los valores cargados por el admin
-- ---------------------------------------------------------------------------
--
-- `signo` se copia del concepto en vez de leerse por join: el catálogo cambia
-- con el tiempo y una liquidación vieja tiene que seguir sumando lo que sumó el
-- día que se cerró. Misma razón por la que `carnes_recepcion_items` congela el
-- costo base.
CREATE TABLE IF NOT EXISTS carnes_liquidacion_gastos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion_id  BIGINT          NOT NULL REFERENCES carnes_liquidaciones(id) ON DELETE CASCADE,
  concepto_id     BIGINT          REFERENCES carnes_conceptos_gasto(id) ON DELETE SET NULL,
  concepto        VARCHAR(80)     NOT NULL,   -- snapshot del nombre
  signo           SMALLINT        NOT NULL DEFAULT 1 CHECK (signo IN (1, -1)),
  valor           NUMERIC(16,2)   NOT NULL DEFAULT 0,
  observaciones   TEXT,
  created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_gastos_liquidacion
  ON carnes_liquidacion_gastos(liquidacion_id);


-- ---------------------------------------------------------------------------
-- 7. carnes_recepciones — Lo que carga el recibidor en UNA sede
-- ---------------------------------------------------------------------------
--
-- Es la unidad de trabajo del recibidor y la unidad de trazabilidad: quién
-- (correo), cuándo (hora), en qué sede, y si el QR de la sede se verificó.
--
-- `sede_verificada` se guarda aunque el flujo exija escanear, porque la pregunta
-- que se va a hacer alguien dentro de seis meses no es "¿se escaneó?" sino "¿ESTE
-- recibo se escaneó?". Un flag global en el código no contesta eso; una columna
-- por fila sí.
--
-- Estados: Borrador → Recibido → Aprobado → Costeado → Enviado_SIESA
--   · Borrador      — el recibidor está digitando, todavía no cerró.
--   · Recibido      — cerró; el admin ya lo ve con toda la trazabilidad.
--   · Aprobado      — el admin dio el visto bueno a las cantidades.
--   · Costeado      — la liquidación cerró y cada ítem tiene su costo ajustado.
--   · Enviado_SIESA — el conector subió el documento.
--   · Rechazado     — el admin lo devolvió (`motivo_rechazo` dice por qué).
--
-- Son cuatro pasos y no dos a propósito: aprobar CANTIDADES y cerrar COSTOS son
-- dos decisiones distintas, y la factura del proveedor casi nunca llega el mismo
-- día que la carne. Si fueran un solo estado, el admin tendría que dejar el
-- recibo sin aprobar hasta que llegue la factura — y mientras tanto nadie sabe
-- si la carne que está en la cava se contó bien.
CREATE TABLE IF NOT EXISTS carnes_recepciones (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion_id     BIGINT        REFERENCES carnes_liquidaciones(id) ON DELETE SET NULL,
  especie            VARCHAR(10)   NOT NULL CHECK (especie IN ('res', 'cerdo')),
  sede_id            BIGINT        NOT NULL REFERENCES carnes_sedes(id),
  fecha_ingreso      DATE          NOT NULL DEFAULT current_date,
  novillos           NUMERIC(10,2) NOT NULL DEFAULT 0,
  estado             VARCHAR(30)   NOT NULL DEFAULT 'Borrador'
                       CHECK (estado IN ('Borrador', 'Recibido', 'Aprobado',
                                         'Costeado', 'Enviado_SIESA', 'Rechazado')),

  -- Trazabilidad del recibidor
  recibido_por       VARCHAR(150),              -- correo
  recibido_at        TIMESTAMPTZ,
  sede_verificada    BOOLEAN       NOT NULL DEFAULT false,
  sede_verificada_at TIMESTAMPTZ,

  -- Trazabilidad del admin
  aprobado_por       VARCHAR(150),
  aprobado_at        TIMESTAMPTZ,
  motivo_rechazo     TEXT,
  costeado_at        TIMESTAMPTZ,
  siesa_at           TIMESTAMPTZ,
  siesa_documento    VARCHAR(60),

  observaciones      TEXT,
  created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_recepciones_estado
  ON carnes_recepciones(estado);
CREATE INDEX IF NOT EXISTS idx_carnes_recepciones_sede_fecha
  ON carnes_recepciones(sede_id, fecha_ingreso DESC);
CREATE INDEX IF NOT EXISTS idx_carnes_recepciones_liquidacion
  ON carnes_recepciones(liquidacion_id);


-- ---------------------------------------------------------------------------
-- 8. carnes_recepcion_items — Los renglones que digita el recibidor
-- ---------------------------------------------------------------------------
--
-- `tipo` separa las tres cosas que el recibidor puede cargar:
--   · 'carne'     — un ítem de la plantilla del admin.
--   · 'vicera'    — un renglón del bloque de vísceras.
--   · 'adicional' — el "Otro / Agregar": llegó algo que no está en la lista. El
--                   recibidor escribe nombre y cantidad, y `plantilla_item_id`
--                   queda NULL. El admin lo ve marcado como adicional y decide
--                   si lo homologa a un código de SIESA antes de subirlo.
--
-- `costo_base` es un SNAPSHOT, no un join contra la plantilla. El admin puede
-- editar el maestro cualquier día; si el costo se leyera por referencia, una
-- recepción de la semana pasada cambiaría de valor sola. Un documento que ya se
-- aprobó no puede cambiar de plata porque alguien corrigió un precio hoy.
--
-- `cantidad` es NUMERIC(12,3): son kilos y llegan con decimales.
CREATE TABLE IF NOT EXISTS carnes_recepcion_items (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recepcion_id       BIGINT          NOT NULL REFERENCES carnes_recepciones(id) ON DELETE CASCADE,
  tipo               VARCHAR(15)     NOT NULL DEFAULT 'carne'
                       CHECK (tipo IN ('carne', 'vicera', 'adicional')),
  plantilla_item_id  BIGINT          REFERENCES carnes_plantilla_items(id) ON DELETE SET NULL,
  vicera_item_id     BIGINT          REFERENCES carnes_viceras_items(id) ON DELETE SET NULL,

  codigo_item        VARCHAR(20),                     -- f120_id; NULL en adicionales sin homologar
  codigo_tabla       INTEGER,
  descripcion        TEXT            NOT NULL,
  orden              INTEGER         NOT NULL DEFAULT 0,

  cantidad           NUMERIC(12,3)   NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
  costo_base         NUMERIC(14,2)   NOT NULL DEFAULT 0,   -- snapshot al momento de recibir

  -- Resultado del costeo (se llenan al pasar a 'Costeado')
  costo_ajustado     NUMERIC(16,4),
  costo_total        NUMERIC(16,2),

  created_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_rec_items_recepcion
  ON carnes_recepcion_items(recepcion_id, orden);
CREATE INDEX IF NOT EXISTS idx_carnes_rec_items_codigo
  ON carnes_recepcion_items(codigo_item);


-- ---------------------------------------------------------------------------
-- Trigger: updated_at automático en todas las tablas
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION carnes_set_updated_at()
RETURNS TRIGGER AS $fn$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

DO $do$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'carnes_sedes',
    'carnes_plantilla_items',
    'carnes_viceras_items',
    'carnes_conceptos_gasto',
    'carnes_liquidaciones',
    'carnes_liquidacion_gastos',
    'carnes_recepciones',
    'carnes_recepcion_items'
  ]
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_' || t
    ) THEN
      EXECUTE format(
        'CREATE TRIGGER %I BEFORE UPDATE ON %I
           FOR EACH ROW EXECUTE FUNCTION carnes_set_updated_at()',
        'set_updated_at_' || t, t
      );
    END IF;
  END LOOP;
END;
$do$;
