-- =============================================================================
-- Migration 004: informe de desposte — el cruce contra lo que contó el recibidor
-- =============================================================================
--
-- El frigorífico emite, por cada entrega, un "Informe Rendimiento por Documento
-- y Mermas Desposte". Es un PDF por SEDE y por LOTE. Trae lo que la planta dice
-- que despachó; la recepción trae lo que el recibidor dice que llegó. Cruzarlos
-- es la única forma de detectar un faltante el mismo día.
--
-- Por qué el informe cuelga de la RECEPCIÓN y no de la liquidación:
-- una recepción YA es una fila por sede, especie y fecha. El PDF también. Es
-- uno a uno y no hay nada que inventar. La liquidación, en cambio, agrupa
-- varias sedes: colgarlo de ahí obligaría a re-partirlo.
--
-- Quién lo sube: el ADMIN, y el recibidor NO lo ve. Si el recibidor pudiera
-- abrir el informe antes de digitar, no contaría la carne: la transcribiría, y
-- el cruce quedaría comparando el PDF contra sí mismo. Los dos números tienen
-- que nacer independientes o esta tabla no sirve para nada.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. Identidad: a qué sede pertenece cada informe
-- ---------------------------------------------------------------------------
--
-- El PDF se identifica solo. Dice `Sub Cliente: MK - 380 - BARRIO LOPEZ`, y esa
-- cadena es la sede. Guardándola acá, el backend puede rechazar un informe
-- adjuntado a la sede equivocada sin que nadie tenga que revisarlo a ojo.
--
-- Es el equivalente del QR para el admin: el recibidor no puede recibir en la
-- sede errada porque escanea; el admin no puede adjuntar el informe de López a
-- Villa Hermosa porque el archivo mismo lo delata.
--
-- NULL = esa sede todavía no tiene su cadena cargada. El informe se acepta
-- igual, pero queda marcado como no verificado: bloquear sedes sin configurar
-- frenaría la operación por un dato de catálogo faltante.
ALTER TABLE carnes_sedes
  ADD COLUMN IF NOT EXISTS subcliente_desposte VARCHAR(120);

COMMENT ON COLUMN carnes_sedes.subcliente_desposte IS
  'Cadena "Sub Cliente" tal como sale en el PDF del frigorífico, ej. "MK - 380 - BARRIO LOPEZ". NULL = sin configurar.';

-- Dos sedes con el mismo sub-cliente haría ambigua la verificación, que es
-- justamente lo que esta columna existe para evitar.
CREATE UNIQUE INDEX IF NOT EXISTS idx_carnes_sedes_subcliente
  ON carnes_sedes(upper(subcliente_desposte))
  WHERE subcliente_desposte IS NOT NULL;


-- ---------------------------------------------------------------------------
-- 2. Diccionario de nombres: PDF <-> plantilla
-- ---------------------------------------------------------------------------
--
-- El informe dice `CHATA DE SOLOMITO`; la plantilla del admin dice lo que diga.
-- Sin esta columna el cruce línea por línea es imposible, y adivinar por
-- parecido de texto es peor que no cruzar: "PUNTA DE ANCA" y "PUNTA DE FALDA"
-- se parecen mucho y son dos cortes distintos.
--
-- Arranca NULL en todo. El cruce por TOTALES funciona igual desde el día uno
-- —no necesita mapear nada—; el detalle línea por línea se va habilitando a
-- medida que se llena el diccionario. Lo que no esté mapeado sale listado como
-- tal, nunca contado como si hubiera cuadrado.
ALTER TABLE carnes_plantilla_items
  ADD COLUMN IF NOT EXISTS nombre_desposte VARCHAR(120);

COMMENT ON COLUMN carnes_plantilla_items.nombre_desposte IS
  'Nombre del producto tal como aparece en el PDF de desposte. NULL = sin mapear todavía.';

CREATE INDEX IF NOT EXISTS idx_carnes_plantilla_nombre_desposte
  ON carnes_plantilla_items(especie, upper(nombre_desposte))
  WHERE nombre_desposte IS NOT NULL;


-- ---------------------------------------------------------------------------
-- 3. carnes_desposte_informes — la cabecera del PDF
-- ---------------------------------------------------------------------------
--
-- Se guarda el archivo (en Storage) Y los datos parseados. Las dos cosas, a
-- propósito:
--
--   · El archivo es la prueba. Dentro de un año, "el sistema dice 133.50" no
--     vale nada si no se puede abrir el PDF que lo dijo.
--   · Los campos parseados son lo que se consulta. Volver a leer el PDF en cada
--     pantalla sería lento y, peor, daría resultados distintos si mañana se
--     corrige el parser: el cruce que el admin aprobó tiene que quedar fijo.
--
-- `texto_extraido` guarda el crudo. Es lo único que permite depurar un parseo
-- raro sin pedirle el archivo al usuario, y lo que permite re-procesar informes
-- viejos si el frigorífico cambia el formato del reporte.
CREATE TABLE IF NOT EXISTS carnes_desposte_informes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recepcion_id       BIGINT        NOT NULL REFERENCES carnes_recepciones(id) ON DELETE CASCADE,

  -- ─── Lo que dice el PDF de sí mismo ───
  lote               VARCHAR(40),               -- "Documento Cliente"
  fecha_desposte     DATE,
  cliente            VARCHAR(120),              -- "380 - JULIO ARBOLEDA SIERRA"
  subcliente         VARCHAR(120),              -- "MK - 380 - BARRIO LOPEZ"
  animales           NUMERIC(10,2),

  -- ─── Totales del informe ───
  -- `kg_finas` es EL número del cruce: los cortes aprovechables.
  -- `kg_subproductos` se guarda pero todavía NO se concilia: falta definir si el
  -- recibidor los pesa como vísceras o como carne. Se muestra, no se suma.
  kg_finas           NUMERIC(12,3),
  kg_subproductos    NUMERIC(12,3),
  kg_peso_pie        NUMERIC(12,3),
  kg_canal_caliente  NUMERIC(12,3),
  kg_canal_fria      NUMERIC(12,3),
  kg_desposte        NUMERIC(12,3),
  kg_aprovechable    NUMERIC(12,3),
  rendimiento_pct    NUMERIC(8,3),
  merma_kg           NUMERIC(12,3),
  merma_pct          NUMERIC(8,3),

  -- ─── El archivo ───
  archivo_path       TEXT          NOT NULL,    -- ruta dentro del bucket privado
  archivo_nombre     TEXT,                      -- nombre original, para descargarlo igual
  archivo_bytes      INTEGER,
  texto_extraido     TEXT,

  -- ─── Verificación de identidad ───
  -- Igual que `sede_verificada` en la recepción: la pregunta dentro de seis
  -- meses no es "¿se validaba la sede?" sino "¿ESTE informe se validó?".
  sede_coincide      BOOLEAN       NOT NULL DEFAULT false,
  fecha_coincide     BOOLEAN       NOT NULL DEFAULT false,

  subido_por         VARCHAR(150),              -- correo del admin
  subido_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
  created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Un informe por recepción. Volver a subirlo REEMPLAZA al anterior: el flujo
-- normal es "me equivoqué de archivo", no "quiero dos".
CREATE UNIQUE INDEX IF NOT EXISTS idx_carnes_desposte_recepcion
  ON carnes_desposte_informes(recepcion_id);

-- El mismo lote adjuntado a dos recepciones es un error de operación: o el
-- informe está en la sede equivocada, o la carne se contó dos veces.
CREATE UNIQUE INDEX IF NOT EXISTS idx_carnes_desposte_lote
  ON carnes_desposte_informes(lote)
  WHERE lote IS NOT NULL;


-- ---------------------------------------------------------------------------
-- 4. carnes_desposte_items — cada línea del PDF
-- ---------------------------------------------------------------------------
--
-- `bloque` respeta la partición del propio informe ('finas' | 'subproductos').
-- No se colapsan en una sola lista porque significan cosas distintas y todavía
-- no está definido cómo se recibe el segundo.
CREATE TABLE IF NOT EXISTS carnes_desposte_items (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  informe_id         BIGINT        NOT NULL REFERENCES carnes_desposte_informes(id) ON DELETE CASCADE,
  bloque             VARCHAR(15)   NOT NULL CHECK (bloque IN ('finas', 'subproductos')),
  producto           VARCHAR(120)  NOT NULL,   -- tal cual el PDF, sin normalizar
  cantidad_kg        NUMERIC(12,3) NOT NULL DEFAULT 0,
  pesajes            INTEGER,
  rendimiento_pct    NUMERIC(8,3),
  promedio_kg        NUMERIC(12,3),
  orden              INTEGER       NOT NULL DEFAULT 0,
  created_at         TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_desposte_items_informe
  ON carnes_desposte_items(informe_id, bloque, orden);


-- ---------------------------------------------------------------------------
-- 5. Storage
-- ---------------------------------------------------------------------------
--
-- El PDF va a un bucket PRIVADO llamado `carnes-desposte`. El backend lo crea
-- solo la primera vez que alguien sube un informe (ver Desposte.model.js), pero
-- si se prefiere crearlo a mano desde el panel de Supabase tiene que ser:
--
--   Nombre:  carnes-desposte
--   Público: NO   <- es prueba de auditoría, no una imagen de catálogo
--
-- Se sirve con URL firmada de corta duración. Un bucket público dejaría los
-- informes de compra de la empresa accesibles con solo adivinar la ruta.
