-- =============================================================================
-- Migration 007: el conector a SIESA y el rastro de cada envío
-- =============================================================================
--
-- Cada recepción va DOS veces a SIESA como ENTRADA_DIRECTA_ALMACEN, las dos en
-- elaboración:
--
--   inicial  cuando el recibidor cierra. Precio de lista. Alguien la anula en
--            SIESA cuando sale la oficial.
--   oficial  cuando el admin costea y aprieta "Enviar a SIESA". Precio
--            ajustado por el factor. Es la que se aprueba.
--
-- Esta tabla es el rastro: qué se mandó, cuándo, quién, qué respondió SIESA, y
-- si salió bien. El payload se guarda ENTERO. Es lo único que permite contestar
-- "¿qué le mandamos exactamente a SIESA el 16 de septiembre?" sin tener que
-- reconstruirlo desde datos que para entonces pueden haber cambiado.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. Bodega de cada sede en SIESA
-- ---------------------------------------------------------------------------
--
-- Cada movimiento lleva `f470_id_bodega`. Es un código de SIESA por sede, y no
-- se puede deducir de nada que ya tengamos. NULL = sin configurar; el envío se
-- bloquea con un mensaje que dice qué sede falta.
ALTER TABLE carnes_sedes
  ADD COLUMN IF NOT EXISTS bodega_siesa VARCHAR(5);

COMMENT ON COLUMN carnes_sedes.bodega_siesa IS
  'Código de bodega en SIESA (f470_id_bodega, 5 caracteres). NULL = sin configurar, no se puede enviar.';


-- ---------------------------------------------------------------------------
-- 2. carnes_siesa_envios — un renglón por cada intento de envío
-- ---------------------------------------------------------------------------
--
-- Los intentos fallidos TAMBIÉN se guardan. Un envío que falló y no dejó rastro
-- es indistinguible de uno que nunca se intentó, y esa diferencia es la que se
-- necesita cuando SIESA dice "acá no llegó nada".
CREATE TABLE IF NOT EXISTS carnes_siesa_envios (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recepcion_id     BIGINT        NOT NULL REFERENCES carnes_recepciones(id) ON DELETE CASCADE,
  liquidacion_id   BIGINT        REFERENCES carnes_liquidaciones(id) ON DELETE SET NULL,
  tipo             VARCHAR(10)   NOT NULL CHECK (tipo IN ('inicial', 'oficial')),
  estado           VARCHAR(10)   NOT NULL CHECK (estado IN ('ok', 'error')),

  -- Identificación en SIESA
  referencia       VARCHAR(12)   NOT NULL,     -- lo que va en PENDIENTE / notas (R23I, R23O)
  consecutivo      INTEGER,                    -- el propio; SIESA lo recalcula
  tipo_docto       VARCHAR(3),

  -- Lo que se mandó y lo que volvió, sin resumir
  payload          JSONB         NOT NULL,
  respuesta        JSONB,
  http_status      INTEGER,
  error            TEXT,

  -- Resumen para la lista, sin abrir el payload
  renglones        INTEGER       NOT NULL DEFAULT 0,
  total_kilos      NUMERIC(12,3) NOT NULL DEFAULT 0,
  total_valor      NUMERIC(16,2) NOT NULL DEFAULT 0,

  -- Trazabilidad
  enviado_por      VARCHAR(150),
  enviado_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
  aviso_anulacion  BOOLEAN       NOT NULL DEFAULT false   -- oficial: ¿salió el correo al que anula?
);

CREATE INDEX IF NOT EXISTS idx_carnes_siesa_envios_recepcion
  ON carnes_siesa_envios(recepcion_id, tipo, enviado_at DESC);
CREATE INDEX IF NOT EXISTS idx_carnes_siesa_envios_fecha
  ON carnes_siesa_envios(enviado_at DESC);


-- ---------------------------------------------------------------------------
-- 3. Configuración
-- ---------------------------------------------------------------------------
--
-- ENTORNO (ya existen en Vercel, compartidas con traslados y dotación):
--   CONNEKTA_BASE_URL      https://servicios.siesacloud.com/api/siesa/v3.1
--   CONNEKTA_ID_COMPANIA   7375
--   CONNI_KEY / CONNI_TOKEN
--   SIESA_ID_SISTEMA       opcional, default 1
--   CARNES_SIESA_ACTIVO    true para que salga algo. Apagado por defecto.
--   CARNES_MAIL_ANULACION  correo(s) de quien anula la entrada inicial
--
-- NEGOCIO (constantes, en src/config/siesa.js → DOCUMENTO_CARNES):
--   tipoDocto, nit, sucursal, unidadMedida, unidadNegocio
