-- =============================================================================
-- Migration 008: a quién se le paga, y con qué tercero entra a SIESA
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. carnes_liquidacion_pagos — el reparto del dinero por beneficiario
-- ---------------------------------------------------------------------------
--
-- La liquidación ya dice CUÁNTO costó la entrega y CÓMO se reparte entre las
-- sedes. Esto dice A QUIÉN se le paga: el ganadero, el frigorífico, el
-- transportador, cada uno con su cuenta.
--
-- Es la misma plata mirada de dos maneras:
--
--   por sede         → a dónde fue la carne      (se calcula: kilos × factura)
--   por beneficiario → de dónde salió el dinero  (se digita: esta tabla)
--
-- Y por eso los dos totales TIENEN que dar igual. Si no dan, o falta un pago
-- o falta un gasto, y costear con esa diferencia reparte entre las sedes una
-- plata que no coincide con la que se giró. El cuadre se valida al costear.
--
-- No se valida contra un maestro de terceros: el nombre y la cuenta se
-- escriben a mano, como en el Excel. Acá lo que importa es que la suma cuadre.
CREATE TABLE IF NOT EXISTS carnes_liquidacion_pagos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion_id  BIGINT        NOT NULL REFERENCES carnes_liquidaciones(id) ON DELETE CASCADE,
  nombre          VARCHAR(120)  NOT NULL,
  cuenta          VARCHAR(80),
  valor           NUMERIC(16,2) NOT NULL DEFAULT 0,
  orden           INTEGER       NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carnes_liq_pagos_liquidacion
  ON carnes_liquidacion_pagos(liquidacion_id, orden);


-- ---------------------------------------------------------------------------
-- 2. Con qué tercero entra la liquidación a SIESA
-- ---------------------------------------------------------------------------
--
-- La entrada oficial no siempre va al mismo proveedor: según cómo se haya
-- comprado el ganado, el tercero puede ser el frigorífico (70329554) o la
-- cuenta de proveedores varios de carnes (PVARIOS-CARNES). Lo decide el admin
-- al enviar, y queda guardado en la liquidación para que dentro de seis meses
-- se pueda saber con cuál se envió.
--
-- NULL = todavía no se eligió. El envío oficial lo exige.
ALTER TABLE carnes_liquidaciones
  ADD COLUMN IF NOT EXISTS siesa_nit      VARCHAR(15),
  ADD COLUMN IF NOT EXISTS siesa_sucursal VARCHAR(3);

COMMENT ON COLUMN carnes_liquidaciones.siesa_nit IS
  'Tercero con el que se envió la entrada oficial a SIESA (f350_id_tercero). NULL = sin enviar.';
