-- =============================================================================
-- Migration 024: retomas de la liquidación de CERDO
-- =============================================================================
--
-- Hasta hoy las retomas del cerdo (Cabeza, Tocino Grasa, Empella, 70/30,
-- Víscera, Cueros y mota, Garra, Hueso blanco) las pesaba el recibidor en cada
-- sede, como renglones tipo 'vicera' de la recepción. Se mueven a la
-- liquidación: las carga el admin UNA vez por entrega, con el precio KL del día,
-- y el total entra a los gastos como el concepto «Retomas» (que RESTA).
--
-- SOLO cerdo. Res no cambia: sigue con sus vísceras en el recibidor y su
-- «Descontar la bonificación de vísceras».
--
-- ─── Qué hace ────────────────────────────────────────────────────────────────
--
--   1. carnes_liquidacion_retomas — kilos y precio de cada retoma por liquidación.
--      `nombre`, `unidad` y `precio_catalogo` son SNAPSHOT: el catálogo
--      (carnes_viceras_items) cambia de precio y una liquidación vieja tiene que
--      seguir diciendo lo que dijo el día que se cargó.
--      `precio` es el que se usó (editable por liquidación); `precio_catalogo` es
--      el que tenía el catálogo en ese momento, para poder mostrar la diferencia.
--
--   2. carnes_liquidacion_gastos.origen — marca la fila de gasto que el sistema
--      DERIVA del panel de retomas ('retomas'). NULL = fila tipeada a mano, como
--      siempre. Esa marca es lo que protege la fila: la grilla de gastos no la
--      edita ni la borra (ver Liquidacion.model.js#guardarGastos).
--
--   3. El concepto «Retomas» de cerdo pasa a signo -1 (resta). En la siembra
--      (sql/002) ya era -1, pero en producción puede haber quedado en +1: sin
--      esto el total de retomas se SUMARÍA al costo en vez de restarse.
--      Las filas de gasto YA guardadas conservan su propio signo (se copia del
--      concepto al guardar): las liquidaciones viejas no cambian de número.
--
-- NO toca carnes_recepcion_items ni nada de res.
--
-- ─── Orden de despliegue ─────────────────────────────────────────────────────
--
--   1. sql/001 (función carnes_set_updated_at) y sql/016 (carnes_viceras_items.unidad)
--   2. sql/024_retomas_liquidacion.sql   ← esta, ANTES del backend
--   3. Backend
--   4. Frontend
--
-- ─── Qué falla si NO se corre antes del backend ──────────────────────────────
--
--   · GET/PUT /api/liquidaciones/:id/retomas responden 503 diciendo que falta
--     esta migración. La liquidación, los gastos y el costeo siguen igual.
--   · Guardar la grilla de gastos de una liquidación de cerdo sigue funcionando
--     (el backend tolera la columna `origen` ausente).
--
-- Idempotente: se puede correr dos veces. Todo o nada.
-- =============================================================================

BEGIN;

-- 0. Precondiciones.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'carnes_set_updated_at'
  ) THEN
    RAISE EXCEPTION
      'Falta la función carnes_set_updated_at (sql/001_create_tables.sql). '
      'Correla antes de esta migración.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'carnes_viceras_items' AND column_name = 'unidad'
  ) THEN
    RAISE EXCEPTION
      'Falta sql/016_visceras_siesa.sql (columna carnes_viceras_items.unidad). '
      'Correla antes de esta migración.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'carnes_liquidacion_gastos'
  ) THEN
    RAISE EXCEPTION
      'Falta sql/001_create_tables.sql (tabla carnes_liquidacion_gastos). '
      'Correla antes de esta migración.';
  END IF;
END $$;


-- 1. carnes_liquidacion_retomas
--
-- UNIQUE (liquidacion_id, vicera_item_id): una retoma del catálogo aparece una
-- sola vez por liquidación, y es el objetivo del upsert (`onConflict`). Es un
-- UNIQUE normal y no un índice de expresión porque PostgREST solo acepta columnas
-- simples ahí. `vicera_item_id` es NULL si la fila del catálogo se borra; los NULL
-- no chocan entre sí.
CREATE TABLE IF NOT EXISTS carnes_liquidacion_retomas (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion_id   BIGINT         NOT NULL REFERENCES carnes_liquidaciones(id) ON DELETE CASCADE,
  vicera_item_id   BIGINT         REFERENCES carnes_viceras_items(id) ON DELETE SET NULL,
  nombre           VARCHAR(80)    NOT NULL,                       -- snapshot
  unidad           VARCHAR(5)     NOT NULL DEFAULT 'KL',          -- snapshot
  kilos            NUMERIC(12,3)  NOT NULL DEFAULT 0 CHECK (kilos >= 0),
  precio           NUMERIC(16,2)  NOT NULL DEFAULT 0 CHECK (precio >= 0),
  precio_catalogo  NUMERIC(16,2)  NOT NULL DEFAULT 0 CHECK (precio_catalogo >= 0), -- snapshot
  orden            INTEGER        NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),

  CONSTRAINT uq_carnes_liquidacion_retomas_item
    UNIQUE (liquidacion_id, vicera_item_id)
);

CREATE INDEX IF NOT EXISTS idx_carnes_liquidacion_retomas_liquidacion
  ON carnes_liquidacion_retomas (liquidacion_id, orden);

DO $do$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'set_updated_at_carnes_liquidacion_retomas'
      AND tgrelid = 'carnes_liquidacion_retomas'::regclass
  ) THEN
    CREATE TRIGGER set_updated_at_carnes_liquidacion_retomas
      BEFORE UPDATE ON carnes_liquidacion_retomas
      FOR EACH ROW EXECUTE FUNCTION carnes_set_updated_at();
  END IF;
END;
$do$;


-- 2. La marca de la fila de gasto derivada.
ALTER TABLE carnes_liquidacion_gastos
  ADD COLUMN IF NOT EXISTS origen VARCHAR(20);

COMMENT ON COLUMN carnes_liquidacion_gastos.origen IS
  'NULL = gasto tipeado a mano. ''retomas'' = lo calcula el sistema desde carnes_liquidacion_retomas: la grilla de gastos no lo edita ni lo borra.';

-- A lo sumo una fila derivada por liquidación y origen.
CREATE UNIQUE INDEX IF NOT EXISTS uq_carnes_gastos_origen_retomas
  ON carnes_liquidacion_gastos (liquidacion_id, origen)
  WHERE origen IS NOT NULL;


-- 3. «Retomas» de cerdo RESTA. Idempotente: si ya está en -1 no toca nada.
UPDATE carnes_conceptos_gasto
   SET signo = -1
 WHERE especie = 'cerdo'
   AND nombre  = 'Retomas'
   AND activo
   AND signo  <> -1;

COMMIT;
